# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Ocelot CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit & Integration Test
      run: dotnet test --no-build --verbosity normal Ocelot.sln /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
    - name: SonarScanner for .NET 8/9 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.4.1
      with:
        sonarProjectKey: Ocelot.Gateway
        sonarProjectName:  Ocelot.Gateway
        sonarOrganization: ocelot
        dotnetBuildArguments: Ocelot.sln
        dotnetDisableTests: true
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/*.opencover.xml" /d:sonar.verbose=true /d:sonar.scm.exclusions.disabled=true /d:sonar.coverage.exclusions="**Test*.cs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      